var data = [
 { "y":"Survey","x":"Classroom","value":1 },	 { "y":"Survey","x":"MOOC","value":0 },	 { "y":"Survey","x":"Online","value":0 },	 { "y":"Survey","x":"Blended","value":7 },
 { "y":"Contributions","x":"Classroom","value":0 },	 { "y":"Contributions","x":"MOOC","value":4 },	 { "y":"Contributions","x":"Online","value":5 },	 { "y":"Contributions","x":"Blended","value":13 },
 { "y":"Interactions","x":"Classroom","value":2 },	 { "y":"Interactions","x":"MOOC","value":7 },	 { "y":"Interactions","x":"Online","value":7 },	 { "y":"Interactions","x":"Blended","value":14 },
 { "y":"Performance","x":"Classroom","value":0 },	 { "y":"Performance","x":"MOOC","value":1 },	 { "y":"Performance","x":"Online","value":1 },	 { "y":"Performance","x":"Blended","value":7 },
 { "y":"Demographics","x":"Classroom","value":0 },	 { "y":"Demographics","x":"MOOC","value":0 },	 { "y":"Demographics","x":"Online","value":1 },	 { "y":"Demographics","x":"Blended","value":1 },
 { "y":"Gaze","x":"Classroom","value":0 },	 { "y":"Gaze","x":"MOOC","value":0 },	 { "y":"Gaze","x":"Online","value":0 },	 { "y":"Gaze","x":"Blended","value":1 },
 { "y":"Content","x":"Classroom","value":0 },	 { "y":"Content","x":"MOOC","value":0 },	 { "y":"Content","x":"Online","value":1 },	 { "y":"Content","x":"Blended","value":1 }
]

var data2 = [ { "y":"Understand Collaboration","x":"Graph","value":7 },	 { "y":"Understand Collaboration","x":"Statistical","value":8 },	 { "y":"Understand Collaboration","x":"Timeline","value":3 },	 { "y":"Understand Collaboration","x":"Wordcloud","value":0 },	 { "y":"Understand Collaboration","x":"Interaction Matrix","value":1 },	 { "y":"Understand Collaboration","x":"Spiral Timeline","value":0 },	 { "y":"Understand Collaboration","x":"Circular Graph","value":0 },	 { "y":"Understand Collaboration","x":"Heatmap","value":1 },	 { "y":"Understand Collaboration","x":"Bubble plot","value":0 },	 { "y":"Understand Collaboration","x":"Concept Map","value":0 },	 { "y":"Understand Collaboration","x":"Radar","value":2 },	 { "y":"Understand Collaboration","x":"Glyph","value":0 },	 { "y":"Understand Collaboration","x":"GeoMap","value":0 },
 { "y":"Instructional Design","x":"Graph","value":2 },	 { "y":"Instructional Design","x":"Statistical","value":12 },	 { "y":"Instructional Design","x":"Timeline","value":1 },	 { "y":"Instructional Design","x":"Wordcloud","value":2 },	 { "y":"Instructional Design","x":"Interaction Matrix","value":1 },	 { "y":"Instructional Design","x":"Spiral Timeline","value":0 },	 { "y":"Instructional Design","x":"Circular Graph","value":1 },	 { "y":"Instructional Design","x":"Heatmap","value":0 },	 { "y":"Instructional Design","x":"Bubble plot","value":2 },	 { "y":"Instructional Design","x":"Concept Map","value":4 },	 { "y":"Instructional Design","x":"Radar","value":0 },	 { "y":"Instructional Design","x":"Glyph","value":2 },	 { "y":"Instructional Design","x":"GeoMap","value":1 },
 { "y":"Understand relationship","x":"Graph","value":0 },	 { "y":"Understand relationship","x":"Statistical","value":3 },	 { "y":"Understand relationship","x":"Timeline","value":0 },	 { "y":"Understand relationship","x":"Wordcloud","value":0 },	 { "y":"Understand relationship","x":"Interaction Matrix","value":0 },	 { "y":"Understand relationship","x":"Spiral Timeline","value":1 },	 { "y":"Understand relationship","x":"Circular Graph","value":0 },	 { "y":"Understand relationship","x":"Heatmap","value":0 },	 { "y":"Understand relationship","x":"Bubble plot","value":0 },	 { "y":"Understand relationship","x":"Concept Map","value":0 },	 { "y":"Understand relationship","x":"Radar","value":0 },	 { "y":"Understand relationship","x":"Glyph","value":0 },	 { "y":"Understand relationship","x":"GeoMap","value":0 },
 { "y":"Promoting Reflection","x":"Graph","value":0 },	 { "y":"Promoting Reflection","x":"Statistical","value":7 },	 { "y":"Promoting Reflection","x":"Timeline","value":0 },	 { "y":"Promoting Reflection","x":"Wordcloud","value":1 },	 { "y":"Promoting Reflection","x":"Interaction Matrix","value":0 },	 { "y":"Promoting Reflection","x":"Spiral Timeline","value":0 },	 { "y":"Promoting Reflection","x":"Circular Graph","value":0 },	 { "y":"Promoting Reflection","x":"Heatmap","value":1 },	 { "y":"Promoting Reflection","x":"Bubble plot","value":3 },	 { "y":"Promoting Reflection","x":"Concept Map","value":2 },	 { "y":"Promoting Reflection","x":"Radar","value":1 },	 { "y":"Promoting Reflection","x":"Glyph","value":0 },	 { "y":"Promoting Reflection","x":"GeoMap","value":0 },
 { "y":"Understand Motivation","x":"Graph","value":0 },	 { "y":"Understand Motivation","x":"Statistical","value":3 },	 { "y":"Understand Motivation","x":"Timeline","value":0 },	 { "y":"Understand Motivation","x":"Wordcloud","value":0 },	 { "y":"Understand Motivation","x":"Interaction Matrix","value":0 },	 { "y":"Understand Motivation","x":"Spiral Timeline","value":0 },	 { "y":"Understand Motivation","x":"Circular Graph","value":0 },	 { "y":"Understand Motivation","x":"Heatmap","value":0 },	 { "y":"Understand Motivation","x":"Bubble plot","value":0 },	 { "y":"Understand Motivation","x":"Concept Map","value":0 },	 { "y":"Understand Motivation","x":"Radar","value":0 },	 { "y":"Understand Motivation","x":"Glyph","value":0 },	 { "y":"Understand Motivation","x":"GeoMap","value":0 },
 { "y":"Exploring usage patterns","x":"Graph","value":0 },	 { "y":"Exploring usage patterns","x":"Statistical","value":5 },	 { "y":"Exploring usage patterns","x":"Timeline","value":0 },	 { "y":"Exploring usage patterns","x":"Wordcloud","value":1 },	 { "y":"Exploring usage patterns","x":"Interaction Matrix","value":0 },	 { "y":"Exploring usage patterns","x":"Spiral Timeline","value":0 },	 { "y":"Exploring usage patterns","x":"Circular Graph","value":0 },	 { "y":"Exploring usage patterns","x":"Heatmap","value":0 },	 { "y":"Exploring usage patterns","x":"Bubble plot","value":1 },	 { "y":"Exploring usage patterns","x":"Concept Map","value":1 },	 { "y":"Exploring usage patterns","x":"Radar","value":0 },	 { "y":"Exploring usage patterns","x":"Glyph","value":0 },	 { "y":"Exploring usage patterns","x":"GeoMap","value":0 },
 { "y":"Exploring learning progress","x":"Graph","value":0 },	 { "y":"Exploring learning progress","x":"Statistical","value":4 },	 { "y":"Exploring learning progress","x":"Timeline","value":0 },	 { "y":"Exploring learning progress","x":"Wordcloud","value":0 },	 { "y":"Exploring learning progress","x":"Interaction Matrix","value":0 },	 { "y":"Exploring learning progress","x":"Spiral Timeline","value":0 },	 { "y":"Exploring learning progress","x":"Circular Graph","value":1 },	 { "y":"Exploring learning progress","x":"Heatmap","value":1 },	 { "y":"Exploring learning progress","x":"Bubble plot","value":0 },	 { "y":"Exploring learning progress","x":"Concept Map","value":0 },	 { "y":"Exploring learning progress","x":"Radar","value":1 },	 { "y":"Exploring learning progress","x":"Glyph","value":0 },	 { "y":"Exploring learning progress","x":"GeoMap","value":0 },
 { "y":"Exploring learning paths","x":"Graph","value":4 },	 { "y":"Exploring learning paths","x":"Statistical","value":1 },	 { "y":"Exploring learning paths","x":"Timeline","value":1 },	 { "y":"Exploring learning paths","x":"Wordcloud","value":0 },	 { "y":"Exploring learning paths","x":"Interaction Matrix","value":0 },	 { "y":"Exploring learning paths","x":"Spiral Timeline","value":0 },	 { "y":"Exploring learning paths","x":"Circular Graph","value":0 },	 { "y":"Exploring learning paths","x":"Heatmap","value":0 },	 { "y":"Exploring learning paths","x":"Bubble plot","value":0 },	 { "y":"Exploring learning paths","x":"Concept Map","value":0 },	 { "y":"Exploring learning paths","x":"Radar","value":0 },	 { "y":"Exploring learning paths","x":"Glyph","value":0 },	 { "y":"Exploring learning paths","x":"GeoMap","value":0 },
 { "y":"Understand Discussion Forums","x":"Graph","value":0 },	 { "y":"Understand Discussion Forums","x":"Statistical","value":1 },	 { "y":"Understand Discussion Forums","x":"Timeline","value":0 },	 { "y":"Understand Discussion Forums","x":"Wordcloud","value":1 },	 { "y":"Understand Discussion Forums","x":"Interaction Matrix","value":0 },	 { "y":"Understand Discussion Forums","x":"Spiral Timeline","value":0 },	 { "y":"Understand Discussion Forums","x":"Circular Graph","value":0 },	 { "y":"Understand Discussion Forums","x":"Heatmap","value":0 },	 { "y":"Understand Discussion Forums","x":"Bubble plot","value":2 },	 { "y":"Understand Discussion Forums","x":"Concept Map","value":1 },	 { "y":"Understand Discussion Forums","x":"Radar","value":0 },	 { "y":"Understand Discussion Forums","x":"Glyph","value":0 },	 { "y":"Understand Discussion Forums","x":"GeoMap","value":0 },
 { "y":"Retention","x":"Graph","value":0 },	 { "y":"Retention","x":"Statistical","value":3 },	 { "y":"Retention","x":"Timeline","value":1 },	 { "y":"Retention","x":"Wordcloud","value":1 },	 { "y":"Retention","x":"Interaction Matrix","value":0 },	 { "y":"Retention","x":"Spiral Timeline","value":0 },	 { "y":"Retention","x":"Circular Graph","value":0 },	 { "y":"Retention","x":"Heatmap","value":0 },	 { "y":"Retention","x":"Bubble plot","value":0 },	 { "y":"Retention","x":"Concept Map","value":0 },	 { "y":"Retention","x":"Radar","value":0 },	 { "y":"Retention","x":"Glyph","value":1 },	 { "y":"Retention","x":"GeoMap","value":0 }
]

var data3 = [
 { "y":"Understand Collaboration","x":"Classroom","value":0 },	 { "y":"Understand Collaboration","x":"MOOC","value":0 },	 { "y":"Understand Collaboration","x":"Online","value":6 },	 { "y":"Understand Collaboration","x":"Blended","value":8 },	 { "y":"Understand Collaboration","x":"Small","value":9 },	 { "y":"Understand Collaboration","x":"Large","value":5 },	 { "y":"Understand Collaboration","x":"Instructor (D)","value":1 },	 { "y":"Understand Collaboration","x":"Students (D)","value":13 },	 { "y":"Understand Collaboration","x":"Instructor (A)","value":11 },	 { "y":"Understand Collaboration","x":"Students (A)","value":2 },	 { "y":"Understand Collaboration","x":"Both (A)","value":1 },
 { "y":"Instructional Design","x":"Classroom","value":3 },	 { "y":"Instructional Design","x":"MOOC","value":3 },	 { "y":"Instructional Design","x":"Online","value":3 },	 { "y":"Instructional Design","x":"Blended","value":5 },	 { "y":"Instructional Design","x":"Small","value":10 },	 { "y":"Instructional Design","x":"Large","value":4 },	 { "y":"Instructional Design","x":"Instructor (D)","value":3 },	 { "y":"Instructional Design","x":"Students (D)","value":11 },	 { "y":"Instructional Design","x":"Instructor (A)","value":6 },	 { "y":"Instructional Design","x":"Students (A)","value":3 },	 { "y":"Instructional Design","x":"Both (A)","value":5 },
 { "y":"Understand relationship","x":"Classroom","value":0 },	 { "y":"Understand relationship","x":"MOOC","value":0 },	 { "y":"Understand relationship","x":"Online","value":2 },	 { "y":"Understand relationship","x":"Blended","value":1 },	 { "y":"Understand relationship","x":"Small","value":0 },	 { "y":"Understand relationship","x":"Large","value":3 },	 { "y":"Understand relationship","x":"Instructor (D)","value":0 },	 { "y":"Understand relationship","x":"Students (D)","value":3 },	 { "y":"Understand relationship","x":"Instructor (A)","value":3 },	 { "y":"Understand relationship","x":"Students (A)","value":0 },	 { "y":"Understand relationship","x":"Both (A)","value":0 },
 { "y":"Promoting Reflection","x":"Classroom","value":0 },	 { "y":"Promoting Reflection","x":"MOOC","value":1 },	 { "y":"Promoting Reflection","x":"Online","value":0 },	 { "y":"Promoting Reflection","x":"Blended","value":6 },	 { "y":"Promoting Reflection","x":"Small","value":5 },	 { "y":"Promoting Reflection","x":"Large","value":2 },	 { "y":"Promoting Reflection","x":"Instructor (D)","value":2 },	 { "y":"Promoting Reflection","x":"Students (D)","value":5 },	 { "y":"Promoting Reflection","x":"Instructor (A)","value":0 },	 { "y":"Promoting Reflection","x":"Students (A)","value":3 },	 { "y":"Promoting Reflection","x":"Both (A)","value":4 },
 { "y":"Understand Motivation","x":"Classroom","value":0 },	 { "y":"Understand Motivation","x":"MOOC","value":0 },	 { "y":"Understand Motivation","x":"Online","value":0 },	 { "y":"Understand Motivation","x":"Blended","value":1 },	 { "y":"Understand Motivation","x":"Small","value":0 },	 { "y":"Understand Motivation","x":"Large","value":1 },	 { "y":"Understand Motivation","x":"Instructor (D)","value":0 },	 { "y":"Understand Motivation","x":"Students (D)","value":1 },	 { "y":"Understand Motivation","x":"Instructor (A)","value":1 },	 { "y":"Understand Motivation","x":"Students (A)","value":0 },	 { "y":"Understand Motivation","x":"Both (A)","value":0 },
 { "y":"Exploring usage patterns","x":"Classroom","value":0 },	 { "y":"Exploring usage patterns","x":"MOOC","value":1 },	 { "y":"Exploring usage patterns","x":"Online","value":0 },	 { "y":"Exploring usage patterns","x":"Blended","value":3 },	 { "y":"Exploring usage patterns","x":"Small","value":0 },	 { "y":"Exploring usage patterns","x":"Large","value":4 },	 { "y":"Exploring usage patterns","x":"Instructor (D)","value":0 },	 { "y":"Exploring usage patterns","x":"Students (D)","value":4 },	 { "y":"Exploring usage patterns","x":"Instructor (A)","value":4 },	 { "y":"Exploring usage patterns","x":"Students (A)","value":0 },	 { "y":"Exploring usage patterns","x":"Both (A)","value":0 },
 { "y":"Exploring learning progress","x":"Classroom","value":0 },	 { "y":"Exploring learning progress","x":"MOOC","value":0 },	 { "y":"Exploring learning progress","x":"Online","value":1 },	 { "y":"Exploring learning progress","x":"Blended","value":4 },	 { "y":"Exploring learning progress","x":"Small","value":4 },	 { "y":"Exploring learning progress","x":"Large","value":1 },	 { "y":"Exploring learning progress","x":"Instructor (D)","value":0 },	 { "y":"Exploring learning progress","x":"Students (D)","value":5 },	 { "y":"Exploring learning progress","x":"Instructor (A)","value":5 },	 { "y":"Exploring learning progress","x":"Students (A)","value":0 },	 { "y":"Exploring learning progress","x":"Both (A)","value":0 },
 { "y":"Exploring learning paths","x":"Classroom","value":0 },	 { "y":"Exploring learning paths","x":"MOOC","value":2 },	 { "y":"Exploring learning paths","x":"Online","value":1 },	 { "y":"Exploring learning paths","x":"Blended","value":3 },	 { "y":"Exploring learning paths","x":"Small","value":4 },	 { "y":"Exploring learning paths","x":"Large","value":2 },	 { "y":"Exploring learning paths","x":"Instructor (D)","value":0 },	 { "y":"Exploring learning paths","x":"Students (D)","value":6 },	 { "y":"Exploring learning paths","x":"Instructor (A)","value":5 },	 { "y":"Exploring learning paths","x":"Students (A)","value":1 },	 { "y":"Exploring learning paths","x":"Both (A)","value":0 },
 { "y":"Understand Discussion Forums","x":"Classroom","value":0 },	 { "y":"Understand Discussion Forums","x":"MOOC","value":1 },	 { "y":"Understand Discussion Forums","x":"Online","value":0 },	 { "y":"Understand Discussion Forums","x":"Blended","value":1 },	 { "y":"Understand Discussion Forums","x":"Small","value":0 },	 { "y":"Understand Discussion Forums","x":"Large","value":2 },	 { "y":"Understand Discussion Forums","x":"Instructor (D)","value":0 },	 { "y":"Understand Discussion Forums","x":"Students (D)","value":2 },	 { "y":"Understand Discussion Forums","x":"Instructor (A)","value":2 },	 { "y":"Understand Discussion Forums","x":"Students (A)","value":0 },	 { "y":"Understand Discussion Forums","x":"Both (A)","value":0 },
 { "y":"Retention","x":"Classroom","value":0 },	 { "y":"Retention","x":"MOOC","value":1 },	 { "y":"Retention","x":"Online","value":0 },	 { "y":"Retention","x":"Blended","value":1 },	 { "y":"Retention","x":"Small","value":0 },	 { "y":"Retention","x":"Large","value":2 },	 { "y":"Retention","x":"Instructor (D)","value":0 },	 { "y":"Retention","x":"Students (D)","value":2 },	 { "y":"Retention","x":"Instructor (A)","value":2 },	 { "y":"Retention","x":"Students (A)","value":0 },	 { "y":"Retention","x":"Both (A)","value":0 }
 ]
 
 var data4 = [
   { "y":"Survey","x":"Graph","value":1 },	 { "y":"Survey","x":"Statistical","value":9 },	 { "y":"Survey","x":"Timeline","value":0 },	 { "y":"Survey","x":"Wordcloud","value":0 },	 { "y":"Survey","x":"Interaction Matrix","value":0 },	 { "y":"Survey","x":"Spiral Timeline","value":0 },	 { "y":"Survey","x":"Circular Graph","value":0 },	 { "y":"Survey","x":"Heatmap","value":0 },	 { "y":"Survey","x":"Bubble plot","value":1 },	 { "y":"Survey","x":"Concept Map","value":0 },	 { "y":"Survey","x":"Radar","value":2 },	 { "y":"Survey","x":"Glyph","value":0 },	 { "y":"Survey","x":"GeoMap","value":0 },
 { "y":"Contributions","x":"Graph","value":5 },	 { "y":"Contributions","x":"Statistical","value":20 },	 { "y":"Contributions","x":"Timeline","value":3 },	 { "y":"Contributions","x":"Wordcloud","value":4 },	 { "y":"Contributions","x":"Interaction Matrix","value":2 },	 { "y":"Contributions","x":"Spiral Timeline","value":1 },	 { "y":"Contributions","x":"Circular Graph","value":0 },	 { "y":"Contributions","x":"Heatmap","value":2 },	 { "y":"Contributions","x":"Bubble plot","value":3 },	 { "y":"Contributions","x":"Concept Map","value":2 },	 { "y":"Contributions","x":"Radar","value":1 },	 { "y":"Contributions","x":"Glyph","value":2 },	 { "y":"Contributions","x":"GeoMap","value":0 },
 { "y":"Interactions","x":"Graph","value":8 },	 { "y":"Interactions","x":"Statistical","value":26 },	 { "y":"Interactions","x":"Timeline","value":4 },	 { "y":"Interactions","x":"Wordcloud","value":3 },	 { "y":"Interactions","x":"Interaction Matrix","value":0 },	 { "y":"Interactions","x":"Spiral Timeline","value":1 },	 { "y":"Interactions","x":"Circular Graph","value":2 },	 { "y":"Interactions","x":"Heatmap","value":2 },	 { "y":"Interactions","x":"Bubble plot","value":3 },	 { "y":"Interactions","x":"Concept Map","value":2 },	 { "y":"Interactions","x":"Radar","value":2 },	 { "y":"Interactions","x":"Glyph","value":2 },	 { "y":"Interactions","x":"GeoMap","value":1 },
 { "y":"Performance","x":"Graph","value":0 },	 { "y":"Performance","x":"Statistical","value":8 },	 { "y":"Performance","x":"Timeline","value":1 },	 { "y":"Performance","x":"Wordcloud","value":3 },	 { "y":"Performance","x":"Interaction Matrix","value":0 },	 { "y":"Performance","x":"Spiral Timeline","value":0 },	 { "y":"Performance","x":"Circular Graph","value":1 },	 { "y":"Performance","x":"Heatmap","value":1 },	 { "y":"Performance","x":"Bubble plot","value":3 },	 { "y":"Performance","x":"Concept Map","value":3 },	 { "y":"Performance","x":"Radar","value":0 },	 { "y":"Performance","x":"Glyph","value":0 },	 { "y":"Performance","x":"GeoMap","value":0 },
 { "y":"Demographics","x":"Graph","value":1 },	 { "y":"Demographics","x":"Statistical","value":2 },	 { "y":"Demographics","x":"Timeline","value":0 },	 { "y":"Demographics","x":"Wordcloud","value":0 },	 { "y":"Demographics","x":"Interaction Matrix","value":0 },	 { "y":"Demographics","x":"Spiral Timeline","value":0 },	 { "y":"Demographics","x":"Circular Graph","value":0 },	 { "y":"Demographics","x":"Heatmap","value":0 },	 { "y":"Demographics","x":"Bubble plot","value":0 },	 { "y":"Demographics","x":"Concept Map","value":0 },	 { "y":"Demographics","x":"Radar","value":0 },	 { "y":"Demographics","x":"Glyph","value":0 },	 { "y":"Demographics","x":"GeoMap","value":0 },
 { "y":"Gaze","x":"Graph","value":0 },	 { "y":"Gaze","x":"Statistical","value":1 },	 { "y":"Gaze","x":"Timeline","value":0 },	 { "y":"Gaze","x":"Wordcloud","value":0 },	 { "y":"Gaze","x":"Interaction Matrix","value":0 },	 { "y":"Gaze","x":"Spiral Timeline","value":0 },	 { "y":"Gaze","x":"Circular Graph","value":0 },	 { "y":"Gaze","x":"Heatmap","value":1 },	 { "y":"Gaze","x":"Bubble plot","value":0 },	 { "y":"Gaze","x":"Concept Map","value":0 },	 { "y":"Gaze","x":"Radar","value":0 },	 { "y":"Gaze","x":"Glyph","value":0 },	 { "y":"Gaze","x":"GeoMap","value":0 },
 { "y":"Content","x":"Graph","value":0 },	 { "y":"Content","x":"Statistical","value":0 },	 { "y":"Content","x":"Timeline","value":0 },	 { "y":"Content","x":"Wordcloud","value":0 },	 { "y":"Content","x":"Interaction Matrix","value":0 },	 { "y":"Content","x":"Spiral Timeline","value":0 },	 { "y":"Content","x":"Circular Graph","value":0 },	 { "y":"Content","x":"Heatmap","value":0 },	 { "y":"Content","x":"Bubble plot","value":0 },	 { "y":"Content","x":"Concept Map","value":2 },	 { "y":"Content","x":"Radar","value":0 },	 { "y":"Content","x":"Glyph","value":0 },	 { "y":"Content","x":"GeoMap","value":0 }
]